### ISSUE TITLE
Fix offline signing

### ISSUE THREAD

**Issue by crocket** [haven-protocol-org/haven-main#4]
This example snippet patches sign_tx to fix offline signing for regular transfers.

```
diff -ur haven-main-1.3.5/src/wallet/wallet2.cpp haven-main-1.3.5-offline/src/wallet/wallet2.cpp
--- haven-main-1.3.5/src/wallet/wallet2.cpp	2021-07-03 18:50:28.000000000 +0900
+++ haven-main-1.3.5-offline/src/wallet/wallet2.cpp	2021-07-13 12:08:18.162331191 +0900
@@ -7272,10 +7272,8 @@
       }
     }
     */
-    bool b = get_pricing_record(pr, current_height);
-    THROW_WALLET_EXCEPTION_IF(!b, error::wallet_internal_error, "Failed to get pricing record");
-    uint32_t fees_version = use_fork_rules(HF_VERSION_OFFSHORE_FEES_V3, 0) ? 3 : use_fork_rules(HF_VERSION_OFFSHORE_FEES_V2, 0) ? 2 : 1;
-    bool use_offshore_tx_version = use_fork_rules(HF_VERSION_OFFSHORE_FULL, 0);
+    uint32_t fees_version = 3;
+    bool use_offshore_tx_version = true;
     bool r = cryptonote::construct_tx_and_get_tx_key(m_account.get_keys(), m_subaddresses, sd.sources, sd.splitted_dsts, sd.change_dts.addr, sd.extra, ptx.tx, sd.unlock_time, tx_key, additional_tx_keys, current_height, pr, fees_version, use_offshore_tx_version, sd.use_rct, rct_config, m_multisig ? &msout : NULL);
     THROW_WALLET_EXCEPTION_IF(!r, error::tx_not_constructed, sd.sources, sd.splitted_dsts, sd.unlock_time, m_nettype);
     // we don't test tx size, because we don't know the current limit, due to not having a blockchain,
```

**Comment by akildemir** [comment]
Fix for this will be included into next fork

**Comment by crocket** [comment]
The snippet is a hack and shouldn't be applied without modification.

**Comment by akildemir** [comment]
@crocket offline signing should be working on the testnet right now. Can you confirm? So we can close this issue.

**Comment by crocket** [comment]
How can I use the testnet?

Is offline signing now working for currency conversion, too?

**Comment by akildemir** [comment]
head over to community testing channel on discord to setup your daemon and wallet. And yes it should be working for all transaction types.

**Comment by crocket** [comment]
I will give it a try tomorrw or soon.

**Comment by crocket** [comment]
I finally started testing, but haven-main-2.0.0-rc3's havend can't sync with testnet. The synchronization stopped.

I think it's better for you to move forward without me.

Someone said currency conversion on an offline wallet still requires price record.

**Comment by crocket** [comment]
I just tested offline signing on main net with haven-main-2.1.0.

On viewing wallet

```
sweep_all address
```

On offline wallet

```
> sign_transfer
Loaded 1 transaction, for xxx, fee xxx XHV, sending xxx XHV to address, 1 dummy output(s), no change, with min ring size 11, dummy encrypted payment ID. XX outputs to import. Is this okay? y
Error: Failed to sign transaction: Failed to get height
```

**Comment by crocket** [comment]
@akildemir Are you busy?

**Comment by akildemir** [comment]
@crocket yes kind of, dealing with the thorchain stuff nowadays but just pushed a fix for this into develop. The signing wallet needed to be online for it to work since we had a partial support for  conversion txs in offline signing but that support didn't make sense and removed but some pieces still left there I think. You can see my last commit in develop. Try with that :).

**Comment by crocket** [comment]
Are you saying that conversions still cannot be signed offline?

**Comment by dshumsky** [comment]
Hello @akildemir 
I got the following tried "offline signing" with v2.2.0-rc1:
```
Error: Failed to sign transaction: Failed to get height
```

**Comment by akildemir** [comment]
@dshumsky we are aware of the issue and it has been fixed in the develop branch. You can use the wallet from that branch if you can build yourself otherwise it is best to wait for the next fork when we will merge develop into master and make a new release.

**Comment by akildemir** [comment]
@crocket yes. Conversions can not be signed offline because it needs pricing record from daemon. Only transfers are possible.

**Comment by crocket** [comment]
Does that mean even hardware wallets can't sign conversions?

**Comment by akildemir** [comment]
@crocket I think the point you are missing is that pricing record age. User can create a tx and try to sign it a year later. But the pricing record can be at most 20 minute old to be used.

**Comment by dshumsky** [comment]
@akildemir is "offline signing" possible in v2.2.0-rc3?

**Comment by crocket** [comment]
Then, if users want to sign offline, they have to sign quick.

**Comment by dshumsky** [comment]
Same problem happens in v2.2.0-rc4:
```
Error: Failed to sign transaction: Failed to get height
```
Is it expected @akildemir? Thank you!

**Comment by akildemir** [comment]
@dshumsky apparently there was a regression on this commit  and it was reverted. I put it back in and should be good now. But since we have to hard code the hard fork version(because it is offline) needed to put the next hf version. So it should be working but your tx wont be accepted by the daemon till next fork.

**Comment by akildemir** [comment]
@crocket yes it would work if you can sign quickly but a lot of change needed to be done to even allow that(embedding pr into tx construction data etc..) we didn't have time for at the moment. Also forcing users to sign quick didn't feel like good thing to do(can easily make mistakes) when there are really easy alternatives such as temporarily moving funds to a normal wallet and convert back to your offline wallet if you want to do conversion. But yes it is theoretically possible  and might do the support in the future.

**Comment by crocket** [comment]
For hardware wallets to support currency conversion, conversions must be signed offline.

**Comment by dshumsky** [comment]
Hi @akildemir. The issue could be closed IMHO. Thanks for the fix

**Comment by crocket** [comment]
I confirmed that 2.2.3 can sign transfers offline. I'm going to create a separate issue for offline signing of currency conversions.
