### ISSUE TITLE
Manually provide release tarballs with all git submodules included.

### ISSUE THREAD

**Issue by crocket** [haven-protocol-org/haven-main#40]
For now, to build haven-main from release tarball, I have to independently download submodules....

This is complex.

**Comment by goshiz** [comment]
you can clone the repo with the specific release tag & submodule in one command :

`git clone https://github.com/haven-protocol-org/haven-main.git test2 --recursive -b v3.0.2
`

**Comment by crocket** [comment]
With that method, linux distribution maintainers have to prepare their own tarballs and provide them to users.

If you provide release tarballs with submodules, then all distributions can just use the official tarballs.
