### ISSUE TITLE
Include git submodules in release tarballs.

### ISSUE THREAD

**Issue by amano-kenji** [haven-protocol-org/haven-main#52]
Because release tarballs don't include git submodules, it's painful to build haven-main.

**Comment by goshiz** [comment]
tarball source code is provided by github, we can't include the submodule in it. 
You can clone the repo and checkout the release tag with --recursive option to get the submodule in one sweep.

`git clone https://github.com/haven-protocol-org/haven-main.git --recursive -b v3.0.2`

**Comment by amano-kenji** [comment]
You can manually upload tarballs with git submodules to https://github.com/haven-protocol-org/haven-main/releases

**Comment by gael-donat** [comment]
We don't want to do manual stuff as it's centralized process and we are trying to avoid it.

**Comment by amano-kenji** [comment]
The problem is that package maintainers are stuck doing the manual process.

Now, the manual process has to be repeated by all linux distributions that want to distribute haven-main package.

**Comment by amano-kenji** [comment]
The real problem is that because I don't understand cmake, I don't know which git submodules are optional.

Some git submodules are skipped, and system libraries are used. I still don't understand why some libraries are optional git submodules.

This is really confusing for package maintainers. It is more confusing than only using system libraries or only using git submodules.

Because I believed in haven protocol, I somehow figured out how to build it. However, the build process really needs to be simplified. Either, make everything git submodules, or make everything system dependencies.
